/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>



int main(void)
{
	int main(void)
	{
	    uint32_t *pRCCGPIOA = (uint32_t*)(0x40023800 + 0x30);
	    *pRCCGPIOA |= 0x01;

	    uint32_t *pGPIOAMode = (uint32_t*)(0x40020000);
	    *pGPIOAMode &= 0xFFFFF3FF; //1111 1111 1111 1111 1111 0011 1111 1111
	    *pGPIOAMode |= 0x01 << 10;

	    uint32_t *pGPIOAState = (uint32_t*)(0x40020000 + 0x14);
	    *pGPIOAState |= 0x01 << 5;
	}

    /* Loop forever */
	for(;;);
}
